### ISSUE TITLE
Roll up window

### ISSUE THREAD

**Issue by jerrychen68** [cydia2020/toyota-automatic-door-locker#1]
How can I roll up window by CAN?

**Comment by cydia2020** [comment]
Hi, unfortunately I don't know, you'll have to sniff the data from the OBD-II port while operating the corresponding `Active Test` in Toyota Techstream.

If you happen to find the corresponding message/data, feel free to open a PR in this repo.

On some Toyota vehicles, there are options in Techstream that allow users to customise the behaviour of their key fobs, where if you long press the lock/unlock keys, the windows will roll up/down. It might be an easier approach.
